language: php

dist: trusty

php:
  - 7.1

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit